const Equipamento = function (equipamento) {
	this.equipamento = equipamento.equipamento;
	this.idequipamento = equipamento.id_equipamento;
	this.horaatual = equipamento.horaatual;
	this.producao = equipamento.producao;
	this.ritmominuto = equipamento.ritmominuto;
	this.ritmodia = equipamento.ritmodia;
	this.ritmometa = equipamento.ritmometa;
	this.metaatual = equipamento.metaatual;
	this.pctmeta = equipamento.pctmeta;
	this.retrabalho = equipamento.retrabalho;
	this.disponibilidade = disponibilidade;
	this.performance = equipamento.performance;
	this.qualidade = equipamento.qualidade;
	this.unidade = equipamento.unidade;
	this.labelparada = equipamento.labelparada;
	this.TempoParado = equipamento.TempoParado;
	this.inicioparada = equipamento.inicioparada;
	this.oee = equipamento.metaoee;
	this.motivoparada = equipamento.descricao;
	this.hoje = equipamento.hoje;
	this.amanha = equipamento.amanha;
	this.hh = equipamento.hh;
	this.mm = equipamento.mm;
	this.sec = equipamento.sec;
}